version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "quick-meet"
    volumes:
      - ./compose-data/postgres-content:/var/lib/pgsql/data
    ports:
      - "5432:5432"